Repository BaguaSys/bagua, pull requests merged in 2021-12, with the labels that each got.

#402 feat(python): associate PyTorch Process Group with Bagua Process Group using cache
  bagua/torch_api/__init__.py
  bagua/torch_api/communication.py
  tests/torch_api/test_process_group.py
Labels: PR: reviewed-approved

#409 feat(python): support find_unused_parameters on BaguaDDP
  bagua/torch_api/data_parallel/bagua_distributed.py
  bagua/torch_api/data_parallel/distributed.py
  tests/torch_api/data_parallel/test_bagua_ddp.py
Labels: PR: unreviewed

#411 chore: update requirements for SQuAD example
  examples/squad/requirements.txt
Labels: PR: unreviewed

#415 fix(python): not found nccl package on CUDA 11.5
  bagua_core/bagua_install_deps.py
Labels: PR: unreviewed

#412 chore: update bagua version in requirements.txt
  examples/benchmark/requirements.txt
  examples/elastic_training/requirements.txt
  examples/imagenet/requirements.txt
  examples/mnist/requirements.txt
  examples/moe/requirements.txt
  examples/squad/requirements.txt
Labels: PR: reviewed-approved

#410 fix: reuse fused parameter tensors in fuse_step
  bagua/torch_api/contrib/fuse/optimizer.py
  examples/benchmark/synthetic_benchmark.py
Labels: PR: unreviewed

#413 fix(python): fix process group compatibility with torch 1.6.0
  bagua/torch_api/communication.py
  bagua/torch_api/data_parallel/distributed.py
Labels: PR: reviewed-approved

#426 feat: introduce NODE_RANK to remove dependency on LOCAL_WORLD_SIZE
  bagua/distributed/launch.py
  bagua/torch_api/communication.py
  bagua/torch_api/contrib/utils/redis_store.py
  bagua/torch_api/env.py
Labels: PR: reviewed-approved

#431 feat: choose bagua service port dynamically
  bagua/torch_api/communication.py
  bagua/torch_api/contrib/utils/redis_store.py
  bagua/torch_api/env.py
  tests/contrib/test_store.py
Labels: PR: reviewed-approved

#434 doc: update doc for cached loader
  bagua/torch_api/contrib/cache_loader.py
Labels: PR: unreviewed

#432 fix: call closure in qadam optimizer step
  bagua/torch_api/algorithms/q_adam.py
Labels: PR: unreviewed

#438 feat: use bagua_module_name to identify different modules
  bagua/torch_api/data_parallel/bagua_distributed.py
  bagua/torch_api/data_parallel/distributed.py
  bagua/torch_api/distributed.py
Labels: PR: partially-approved

#433 feat: add algorithm registry
  bagua/torch_api/algorithms/__init__.py
  bagua/torch_api/algorithms/base.py
Labels: PR: partially-approved

#445 fix(python): fix ci random fail
  bagua/service/autotune_service.py
  bagua/torch_api/data_parallel/bagua_distributed.py
Labels: PR: unreviewed

#449 feat: add compatibility for NCCL version under 2.10
  rust/bagua-core/bagua-core-internal/src/communicators/mod.rs
  tests/comm/test_communicator.py
Labels: PR: unreviewed

#437 feat: add broadcast object api
  bagua/torch_api/communication.py
  tests/comm/test_communicator.py
Labels: PR: unreviewed

#448 doc: update allreduce API doc
  bagua/torch_api/communication.py
Labels: PR: unreviewed

#454 fix: fix need_reset condition
  bagua/torch_api/data_parallel/bagua_distributed.py
Labels: PR: unreviewed

#447 fix: do negotiation in async native op
  bagua/torch_api/algorithms/async_model_average.py
  rust/bagua-core/bagua-core-internal/src/comm_ops/decentralized_full_precision_asynchronous.rs
  rust/bagua-core/bagua-core-internal/src/cuda_utils.rs
  rust/bagua-core/bagua-core-internal/src/datatypes/mod.rs
  rust/bagua-core/bagua-core-py/src/lib.rs
  tests/torch_api/test_async_model_average.py
Labels: PR: unreviewed

#452 fix: fix find_unused_parameters
  bagua/service/autotune_service.py
  bagua/torch_api/communication.py
  bagua/torch_api/data_parallel/distributed.py
Labels: PR: unreviewed

#459 fix: fix qadam non-deterministic
  .buildkite/scripts/benchmark_master.sh
  .buildkite/scripts/benchmark_worker.sh
  bagua/torch_api/bucket.py
Labels: PR: unreviewed

#460 chore(python): support for elastic_bagua
  bagua/torch_api/distributed.py
Labels: PR: partially-approved

#462 chore: add installation script for bagua master and format shell scripts
  .buildkite/scripts/benchmark.sh
  .buildkite/scripts/benchmark_master.sh
  .buildkite/scripts/benchmark_worker.sh
  install.sh
  install_master.sh
Labels: PR: unreviewed

#465 fix: add `LIBRARY_PATH` env in `install_master.sh`
  install_master.sh
Labels: PR: unreviewed
